FROM hardcoreeng/front-base:v20250916
WORKDIR /app

COPY pods/front/bundle/bundle.js ./
COPY pods/front/bundle/bundle.js.map ./
COPY dev/prod/dist/ ./dist/

COPY branding/kanbee/branding.json ./dist/branding.json
COPY branding/kanbee/kanbee/ ./dist/kanbee/

EXPOSE 8080
CMD [ "node", "./bundle.js" ]
